package input

type InputIDFeatureDetail struct {
	ID int `uri:"id" binding:"required"`
}

type FeatureDetailInput struct {
	FeatureID   int    `json:"feature_id" form:"feature_id"`
	PathOfFile  string `json:"path_of_file" form:"path_of_file"`
	Title       string `json:"title" form:"title"`
	Code        string `json:"code" form:"code"`
	Description string `json:"description" form:"description"`
	AuthorName  string `json:"author_name" form:"author_name"`
}

//Generated by Micagen at 25 Mei 2022
