package input

type InputIDFeature struct {
	ID int `uri:"id" binding:"required"`
}

type FeatureInput struct {
	FeatureName        string `json:"feature_name" form:"feature_name"`
	FeatureDescription string `json:"feature_description" form:"feature_description"`
}

//Generated by Micagen at 25 Mei 2022
