package service

import (
	"documentation/entity"
	"documentation/input"
	"documentation/repository"
	"errors"

	"golang.org/x/crypto/bcrypt"
)

type UserService interface {
	UserServiceGetAll() ([]entity.User, error)
	UserServiceGetByID(inputID input.InputIDUser) (entity.User, error)
	UserServiceCreate(input input.UserInput) (entity.User, error)
	UserServiceUpdate(inputID input.InputIDUser, inputData input.UserInput) (entity.User, error)
	UserServiceDeleteByID(inputID input.InputIDUser) (bool, error)
	Login(input input.LoginInput) (entity.User, error)
}
type userService struct {
	repository repository.UserRepository
}

func NewUserService(repository repository.UserRepository) *userService {
	return &userService{repository}
}

func (s *userService) Login(input input.LoginInput) (entity.User, error) {
	username := input.Username
	password := input.Password

	user, err := s.repository.FindByUsername(username)

	if err != nil {
		return user, err
	}

	if user.ID == 0 {
		return user, errors.New("no user found")
	}

	err = bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(password))
	if err != nil {
		return user, err
	}
	return user, nil
}

func (s *userService) UserServiceCreate(input input.UserInput) (entity.User, error) {
	user := entity.User{}
	user.Username = input.Username
	passwordHash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.MinCost)
	if err != nil {
		return user, err
	}
	user.Password = string(passwordHash)
	user.Name = input.Name
	user.Role = input.Role
	newUser, err := s.repository.SaveUser(user)
	if err != nil {
		return newUser, err
	}
	return newUser, nil
}

func (s *userService) UserServiceUpdate(inputID input.InputIDUser, inputData input.UserInput) (entity.User, error) {
	user, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return user, err
	}
	user.Username = inputData.Username

	passwordHash, err := bcrypt.GenerateFromPassword([]byte(inputData.Password), bcrypt.MinCost)
	if err != nil {
		return user, err
	}
	err = bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(inputData.Password))
	password := ""
	if err != nil {
		password = string(passwordHash)
	} else {
		password = user.Password
	}
	user.Password = password
	user.Name = inputData.Name
	user.Role = inputData.Role

	updatedUser, err := s.repository.UpdateUser(user)

	if err != nil {
		return updatedUser, err
	}
	return updatedUser, nil
}

func (s *userService) UserServiceGetByID(inputID input.InputIDUser) (entity.User, error) {
	user, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return user, err
	}
	return user, nil
}

func (s *userService) UserServiceGetAll() ([]entity.User, error) {
	users, err := s.repository.FindAllUser()
	if err != nil {
		return users, err
	}
	return users, nil
}

func (s *userService) UserServiceDeleteByID(inputID input.InputIDUser) (bool, error) {
	_, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return false, err
	}
	_, err = s.repository.DeleteByIDUser(inputID.ID)
	if err != nil {
		return false, err
	}
	return true, nil
}

//Generated by Micagen at 25 Mei 2022
