package repository

import (
	"documentation/entity"
	"fmt"

	"gorm.io/gorm"
)

type PrdRepository interface {
	SavePrd(prd entity.Prd) (entity.Prd, error)
	UpdatePrd(prd entity.Prd) (entity.Prd, error)
	FindByIDPrd(ID int) (entity.Prd, error)
	FindAllPrd() ([]entity.Prd, error)
	DeleteByIDPrd(ID int) (entity.Prd, error)
	TotalFetchData(search string, page int, size int) (int, error)
	FindAll(search string, page int, size int) ([]entity.Prd, error)
}

type prdRepository struct {
	db *gorm.DB
}

func NewPrdRepository(db *gorm.DB) *prdRepository {
	return &prdRepository{db}
}

func (r *prdRepository) SavePrd(prd entity.Prd) (entity.Prd, error) {
	err := r.db.Create(&prd).Error
	if err != nil {
		return prd, err
	}
	return prd, nil

}
func (r *prdRepository) FindByIDPrd(ID int) (entity.Prd, error) {
	var prd entity.Prd
	err := r.db.Where("id = ? ", ID).Find(&prd).Error
	if err != nil {
		return prd, err
	}
	return prd, nil

}
func (r *prdRepository) UpdatePrd(prd entity.Prd) (entity.Prd, error) {
	err := r.db.Save(&prd).Error
	if err != nil {
		return prd, err
	}
	return prd, nil

}
func (r *prdRepository) FindAllPrd() ([]entity.Prd, error) {
	var prds []entity.Prd
	err := r.db.Find(&prds).Error
	if err != nil {
		return prds, err
	}
	return prds, nil

}
func (r *prdRepository) DeleteByIDPrd(ID int) (entity.Prd, error) {
	var prd entity.Prd
	err := r.db.Where("id = ? ", ID).Delete(&prd).Error
	if err != nil {
		return prd, err
	}
	return prd, nil

}

func (r *prdRepository) FindAll(search string, page int, size int) ([]entity.Prd, error) {
	var feature []entity.Prd
	searchQuery := search
	sql := "SELECT * FROM prds WHERE 1=1 "
	if searchQuery != "" {
		sql = fmt.Sprintf("%s AND (document_name LIKE '%%%s%%') ", sql, searchQuery)
	}
	start := (page * size)
	limit := 0
	if start < 0 {
		limit = 0
	} else {
		limit = start
	}
	length := size

	sql = fmt.Sprintf("%s ORDER BY id DESC LIMIT %d OFFSET %d", sql, length, limit)

	err := r.db.Raw(sql).Scan(&feature).Error
	if err != nil {
		return feature, err
	}
	return feature, nil

}

func (r *prdRepository) TotalFetchData(search string, page int, size int) (int, error) {
	var features []entity.Prd
	searchQuery := search
	sql := "SELECT * FROM prds WHERE 1=1 "
	// SELECT * FROM users where 1=1 and (nama_lengkap LIKE '%joko%' OR user_name like '%joko%')
	if searchQuery != "" {
		sql = fmt.Sprintf("%s AND (document_name LIKE '%%%s%%') ", sql, searchQuery)
	}

	err := r.db.Raw(sql).Scan(&features).Error
	if err != nil {
		return len(features), err
	}
	return len(features), nil
}

//Generated by Micagen at 25 Mei 2022
