package formatter

import (
	"documentation/entity"

	"github.com/ekokurniadi/indodate"
)

type FeatureDetailFormatter struct {
	ID          int    `json:"id"`
	FeatureID   int    `json:"feature_id"`
	PathOfFile  string `json:"path_of_file"`
	Title       string `json:"title"`
	Code        string `json:"code"`
	Description string `json:"description"`
	AuthorName  string `json:"author_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	FeatureName string `json:"feature_name"`
}

func FormatFeatureDetail(featuredetail entity.FeatureDetail) FeatureDetailFormatter {
	featuredetailFormatter := FeatureDetailFormatter{}
	featuredetailFormatter.ID = featuredetail.ID
	featuredetailFormatter.FeatureName = featuredetail.FeatureName
	featuredetailFormatter.FeatureID = featuredetail.FeatureID
	featuredetailFormatter.PathOfFile = featuredetail.PathOfFile
	featuredetailFormatter.Title = featuredetail.Title
	featuredetailFormatter.Code = featuredetail.Code
	featuredetailFormatter.Description = featuredetail.Description
	featuredetailFormatter.AuthorName = featuredetail.AuthorName
	featuredetailFormatter.CreatedAt = indodate.LetterDate(featuredetail.CreatedAt)
	featuredetailFormatter.UpdatedAt = indodate.LetterDate(featuredetail.UpdatedAt)
	return featuredetailFormatter
}
func FormatFeatureDetails(featuredetails []entity.FeatureDetail) []FeatureDetailFormatter {
	featuredetailsFormatter := []FeatureDetailFormatter{}
	for _, featuredetail := range featuredetails {
		featuredetailFormatter := FormatFeatureDetail(featuredetail)
		featuredetailsFormatter = append(featuredetailsFormatter, featuredetailFormatter)
	}
	return featuredetailsFormatter
}

//Generated by Micagen at 25 Mei 2022
