package formatter

import (
	"documentation/entity"

	"github.com/ekokurniadi/indodate"
)

type FeatureFormatter struct {
	ID                 int    `json:"id"`
	FeatureName        string `json:"feature_name"`
	FeatureDescription string `json:"feature_description"`
	CreatedAt          string `json:"created_at"`
}

func FormatFeature(feature entity.Feature) FeatureFormatter {
	featureFormatter := FeatureFormatter{}
	featureFormatter.ID = feature.ID
	featureFormatter.FeatureName = feature.FeatureName
	featureFormatter.FeatureDescription = feature.FeatureDescription
	featureFormatter.CreatedAt = indodate.LetterDate(feature.CreatedAt)
	return featureFormatter
}
func FormatFeatures(features []entity.Feature) []FeatureFormatter {
	featuresFormatter := []FeatureFormatter{}
	for _, feature := range features {
		featureFormatter := FormatFeature(feature)
		featuresFormatter = append(featuresFormatter, featureFormatter)
	}
	return featuresFormatter
}

//Generated by Micagen at 25 Mei 2022
