package formatter

import "documentation/entity"

type PrdFormatter struct {
	ID           int    `json:"id"`
	DocumentName string `json:"document_name"`
	Description  string `json:"description"`
	Link         string `json:"link"`
}

func FormatPrd(prd entity.Prd) PrdFormatter {
	prdFormatter := PrdFormatter{}
	prdFormatter.ID = prd.ID
	prdFormatter.DocumentName = prd.DocumentName
	prdFormatter.Description = prd.Description
	prdFormatter.Link = prd.Link
	return prdFormatter
}
func FormatPrds(prds []entity.Prd) []PrdFormatter {
	prdsFormatter := []PrdFormatter{}
	for _, prd := range prds {
		prdFormatter := FormatPrd(prd)
		prdsFormatter = append(prdsFormatter, prdFormatter)
	}
	return prdsFormatter
}

//Generated by Micagen at 25 Mei 2022
